#!/bin/bash

FILE=~/.todo_list.todo

# checking flags and setting mode based on these flags
if [ "$#" -ne 0 ]; then
    case "$1" in
        "--create")     mode=create ;;
        "-c")           mode=create ;;
        "--help")       mode=help ;;
        "-h")           mode=help ;;
        *)              mode=help ;;
    esac
else
    mode=list
fi

# loading configuration from /etc/todo_list.conf
typeset -A config
config=(
    [todo_count]="0"
)
if [ -f $FILE ]; then
    while read line; do
        if echo $line | grep -F = &>/dev/null; then
            varname=$(echo "$line" | cut -d '=' -f 1)
            config[$varname]=$(echo "$line" | cut -d '=' -f 2-)
        fi
    done < $FILE
fi

case "$mode" in
    "help") # Displaying help message
        echo "Usage: todo [options <arg>]"
        echo "Options:"
        echo "    -c, --create <text>       - creates new entry"
        echo "    -h, --help                - displays help message"
        ;;
    "list") # Showing list of ToDos
        for i in $(seq 1 ${config[todo_count]}); do
            echo $i
        done
        ;;
    "create") # Creating new element on list
        echo "Created"
esac

touch $FILE
echo "" > $FILE
for index in ${!config[*]}; do
    echo "$index=${config[$index]}" >> $FILE
done
